pub mod battery;
pub mod charging;
pub mod fast_charging;
pub mod power_management;
pub mod solar_panel;
pub mod wireless_charging;
pub use battery::Battery;
pub use charging::Charging;
pub use power_management::PowerManager;
