pub mod usb;
pub mod i2c;
pub mod spi;
pub mod uart;
pub mod gpio;
pub mod pci;
pub mod i2c_master;
pub use usb::USBInterface;
pub use i2c::{I2CInterface, I2CBus};
pub use spi::SPIInterface;
pub use uart::UARTInterface;
pub use gpio::GPIOInterface;
pub use pci::PCIInterface;
pub use i2c_master::{I2CMaster, BQ27441Reader};
